-- AlterTable
ALTER TABLE `leads` ADD COLUMN `address` VARCHAR(191) NULL,
    ADD COLUMN `first_name` VARCHAR(191) NULL,
    ADD COLUMN `last_name` VARCHAR(191) NULL,
    ADD COLUMN `lgref` VARCHAR(191) NULL,
    ADD COLUMN `locations` VARCHAR(191) NULL,
    ADD COLUMN `phone` VARCHAR(191) NULL,
    ADD COLUMN `place_id` VARCHAR(191) NULL,
    ADD COLUMN `restaurant_name` VARCHAR(191) NULL,
    ADD COLUMN `sms_consent` BOOLEAN NULL,
    ADD COLUMN `utm_campaign` VARCHAR(191) NULL,
    ADD COLUMN `utm_content` VARCHAR(191) NULL,
    ADD COLUMN `utm_medium` VARCHAR(191) NULL,
    ADD COLUMN `utm_source` VARCHAR(191) NULL,
    ADD COLUMN `utm_term` VARCHAR(191) NULL,
    MODIFY `revenue` DOUBLE NULL,
    MODIFY `aov` DOUBLE NULL,
    MODIFY `platform` VARCHAR(191) NULL,
    MODIFY `monthly_loss` DOUBLE NULL;
