// Error codes as const for type safety
export const ErrorCodes = {
  // Order errors
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_ALREADY_PAID: "ORDER_ALREADY_PAID",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  INVALID_PAYMENT_STATUS_TRANSITION: "INVALID_PAYMENT_STATUS_TRANSITION",
  INVALID_FULFILLMENT_STATUS_TRANSITION: "INVALID_FULFILLMENT_STATUS_TRANSITION",
  FULFILLMENT_REQUIRES_PAYMENT: "FULFILLMENT_REQUIRES_PAYMENT",
  MENU_ITEMS_UNAVAILABLE: "MENU_ITEMS_UNAVAILABLE",
  MERCHANT_ID_REQUIRED: "MERCHANT_ID_REQUIRED",

  // Merchant errors
  MERCHANT_NOT_FOUND: "MERCHANT_NOT_FOUND",
  MERCHANT_SLUG_TAKEN: "MERCHANT_SLUG_TAKEN",
  COMPANY_NOT_FOUND: "COMPANY_NOT_FOUND",
  COMPANY_SLUG_TAKEN: "COMPANY_SLUG_TAKEN",
  COMPANY_ALREADY_EXISTS: "COMPANY_ALREADY_EXISTS",

  // Menu errors
  MENU_NOT_FOUND: "MENU_NOT_FOUND",
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  MENU_ITEM_NOT_FOUND: "MENU_ITEM_NOT_FOUND",

  // Auth errors
  AUTH_EMAIL_EXISTS: "AUTH_EMAIL_EXISTS",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_INVALID_STYTCH_SESSION: "AUTH_INVALID_STYTCH_SESSION",
  AUTH_MISSING_EMAIL: "AUTH_MISSING_EMAIL",
  AUTH_MISSING_SESSION_TOKEN: "AUTH_MISSING_SESSION_TOKEN",
  AUTH_STYTCH_CALLBACK_FAILED: "AUTH_STYTCH_CALLBACK_FAILED",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_INVALID_RESET_TOKEN: "AUTH_INVALID_RESET_TOKEN",
  AUTH_RESET_TOKEN_EXPIRED: "AUTH_RESET_TOKEN_EXPIRED",
  AUTH_VALIDATION_FAILED: "AUTH_VALIDATION_FAILED",

  // OTP errors
  OTP_NOT_FOUND: "OTP_NOT_FOUND",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_INVALID: "OTP_INVALID",
  OTP_MAX_ATTEMPTS: "OTP_MAX_ATTEMPTS",
  OTP_ALREADY_VERIFIED: "OTP_ALREADY_VERIFIED",
  OTP_INVALID_PHONE: "OTP_INVALID_PHONE",
  OTP_SMS_FAILED: "OTP_SMS_FAILED",

  // Gift card errors
  GIFTCARD_NOT_FOUND: "GIFTCARD_NOT_FOUND",
  GIFTCARD_NO_BALANCE: "GIFTCARD_NO_BALANCE",
  GIFTCARD_INSUFFICIENT_BALANCE: "GIFTCARD_INSUFFICIENT_BALANCE",
  GIFTCARD_GENERATION_FAILED: "GIFTCARD_GENERATION_FAILED",

  // Loyalty errors
  LOYALTY_MEMBER_NOT_FOUND: "LOYALTY_MEMBER_NOT_FOUND",
  LOYALTY_POINTS_ALREADY_AWARDED: "LOYALTY_POINTS_ALREADY_AWARDED",
  LOYALTY_NEGATIVE_BALANCE: "LOYALTY_NEGATIVE_BALANCE",

  // Payment errors
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_VERIFICATION_FAILED: "PAYMENT_VERIFICATION_FAILED",
  PAYMENT_AMOUNT_MISMATCH: "PAYMENT_AMOUNT_MISMATCH",
  PAYMENT_STATUS_INVALID: "PAYMENT_STATUS_INVALID",
  PAYMENT_ALREADY_PROCESSED: "PAYMENT_ALREADY_PROCESSED",

  // Stripe Connect errors
  STRIPE_CONNECT_NOT_CONFIGURED: "STRIPE_CONNECT_NOT_CONFIGURED",
  STRIPE_CONNECT_ACCOUNT_NOT_FOUND: "STRIPE_CONNECT_ACCOUNT_NOT_FOUND",
  STRIPE_CONNECT_CHARGES_NOT_ENABLED: "STRIPE_CONNECT_CHARGES_NOT_ENABLED",
  STRIPE_CONNECT_MISSING_TENANT: "STRIPE_CONNECT_MISSING_TENANT",
  STRIPE_CONNECT_OAUTH_FAILED: "STRIPE_CONNECT_OAUTH_FAILED",
  STRIPE_CONNECT_ALREADY_CONNECTED: "STRIPE_CONNECT_ALREADY_CONNECTED",
  STRIPE_CONNECT_DISCONNECT_FAILED: "STRIPE_CONNECT_DISCONNECT_FAILED",

  // Subscription errors
  SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTION_NOT_FOUND",
  SUBSCRIPTION_NOT_CANCELLABLE: "SUBSCRIPTION_NOT_CANCELLABLE",
  SUBSCRIPTION_PRICE_NOT_CONFIGURED: "SUBSCRIPTION_PRICE_NOT_CONFIGURED",
  TENANT_NOT_FOUND: "TENANT_NOT_FOUND",

  // Invoice errors
  INVOICE_NOT_FOUND: "INVOICE_NOT_FOUND",
  INVOICE_ALREADY_EXISTS: "INVOICE_ALREADY_EXISTS",
  CATERING_ORDER_NOT_FOUND: "CATERING_ORDER_NOT_FOUND",

  // Generator errors
  GENERATOR_NOT_FOUND: "GENERATOR_NOT_FOUND",
  GENERATOR_ALREADY_IN_PROGRESS: "GENERATOR_ALREADY_IN_PROGRESS",
  GENERATOR_FAILED: "GENERATOR_FAILED",
  GOOGLE_PLACES_FETCH_FAILED: "GOOGLE_PLACES_FETCH_FAILED",

  // Claim errors
  CLAIM_FAILED: "CLAIM_FAILED",
  CLAIM_TENANT_NOT_FOUND: "CLAIM_TENANT_NOT_FOUND",
  CLAIM_TENANT_NOT_TRIAL: "CLAIM_TENANT_NOT_TRIAL",
  CLAIM_EMAIL_EXISTS: "CLAIM_EMAIL_EXISTS",

  // Integration errors
  POS_PROVIDER_NOT_FOUND: "POS_PROVIDER_NOT_FOUND",
  INTEGRATION_NOT_CONNECTED: "INTEGRATION_NOT_CONNECTED",
  INTEGRATION_TOKEN_EXPIRED: "INTEGRATION_TOKEN_EXPIRED",
  INTEGRATION_OAUTH_STATE_INVALID: "INTEGRATION_OAUTH_STATE_INVALID",
  SQUARE_CATALOG_SYNC_FAILED: "SQUARE_CATALOG_SYNC_FAILED",
  SQUARE_SYNC_ALREADY_RUNNING: "SQUARE_SYNC_ALREADY_RUNNING",
  SQUARE_NOT_CONFIGURED: "SQUARE_NOT_CONFIGURED",
  SQUARE_ORDER_PUSH_FAILED: "SQUARE_ORDER_PUSH_FAILED",
  SQUARE_ORDER_NOT_FOUND: "SQUARE_ORDER_NOT_FOUND",
  SQUARE_ORDER_UPDATE_FAILED: "SQUARE_ORDER_UPDATE_FAILED",
  SQUARE_ORDER_CANCEL_FAILED: "SQUARE_ORDER_CANCEL_FAILED",
  SQUARE_MISSING_EXTERNAL_MAPPING: "SQUARE_MISSING_EXTERNAL_MAPPING",
  SQUARE_MISSING_LOCATION: "SQUARE_MISSING_LOCATION",
  SQUARE_MISSING_DELIVERY_ADDRESS: "SQUARE_MISSING_DELIVERY_ADDRESS",
  SQUARE_WEBHOOK_NOT_CONFIGURED: "SQUARE_WEBHOOK_NOT_CONFIGURED",
  SQUARE_WEBHOOK_SIGNATURE_INVALID: "SQUARE_WEBHOOK_SIGNATURE_INVALID",
  SQUARE_WEBHOOK_PROCESSING_FAILED: "SQUARE_WEBHOOK_PROCESSING_FAILED",

  // GBP (Google Business Profile) errors
  GBP_NOT_CONFIGURED: "GBP_NOT_CONFIGURED",
  GBP_SYNC_FAILED: "GBP_SYNC_FAILED",
  GBP_ACCOUNT_FETCH_FAILED: "GBP_ACCOUNT_FETCH_FAILED",
  GBP_LOCATION_FETCH_FAILED: "GBP_LOCATION_FETCH_FAILED",

  // Generic errors
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NETWORK_ERROR: "NETWORK_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
