name: Build Base Image - Prod (US-West)

on:
  workflow_dispatch:

jobs:
  build-base-prod:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-west-1
      ECR_REPOSITORY: plovr/grow-base

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Base Image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f Dockerfile.base .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
